name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      # Replace the step below with fastai/workflows/nbdev-ci@master
      # if https://github.com/fastai/workflows/pull/75 is ever merged
      - uses: spather/fastai-workflows/nbdev-ci@skip-checkout
        with:
          skip_checkout: 'true'
